version: "3"
services:
    redis:
        image: harbor-bj.devopshub.cn/docker-training/redis:alpine
        ports:
            - "6379"
    db:
        image: harbor-bj.devopshub.cn/docker-training/postgres:9.4
        volumes:
            - db-data:/var/lib/postgresql/data
    vote:
        image: leixuacr.azurecr.io/linux/vote:latest
        ports:
            - 5000:80
        depends_on:
            - redis
    result:
        image: leixuacr.azurecr.io/linux/result:latest
        ports:
            - 5001:80
        depends_on:
            - db
    worker:
        image: leixuacr.azurecr.io/linux/worker:latest